// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MyAnimeCollection.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241221184446_SyncDatabase")]
    partial class SyncDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AvaliacaoAnime", b =>
                {
                    b.Property<int>("AvaliacaoAnimeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AvaliacaoAnimeId"));

                    b.Property<string>("AnimeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comentario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Nota")
                        .HasColumnType("int");

                    b.Property<int>("UtilizadorId")
                        .HasColumnType("int");

                    b.HasKey("AvaliacaoAnimeId");

                    b.HasIndex("UtilizadorId");

                    b.ToTable("AvaliacoesAnime");
                });

            modelBuilder.Entity("AvaliacaoListaUtilizador", b =>
                {
                    b.Property<int>("AvaliacaoListaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AvaliacaoListaId"));

                    b.Property<int>("Avaliacao")
                        .HasColumnType("int");

                    b.Property<int>("ListaUtilizadorId")
                        .HasColumnType("int");

                    b.Property<int>("UtilizadorId")
                        .HasColumnType("int");

                    b.HasKey("AvaliacaoListaId");

                    b.HasIndex("ListaUtilizadorId");

                    b.HasIndex("UtilizadorId");

                    b.ToTable("AvaliacoesListasUtilizador");
                });

            modelBuilder.Entity("ListaAnime", b =>
                {
                    b.Property<int>("ListaAnimeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ListaAnimeId"));

                    b.Property<string>("AnimeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ListaUtilizadorId")
                        .HasColumnType("int");

                    b.HasKey("ListaAnimeId");

                    b.HasIndex("ListaUtilizadorId");

                    b.ToTable("ListaAnimes");
                });

            modelBuilder.Entity("ListaUtilizador", b =>
                {
                    b.Property<int>("ListaUtilizadorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ListaUtilizadorId"));

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UtilizadorId")
                        .HasColumnType("int");

                    b.HasKey("ListaUtilizadorId");

                    b.HasIndex("UtilizadorId");

                    b.ToTable("ListasUtilizador");
                });

            modelBuilder.Entity("Utilizador", b =>
                {
                    b.Property<int>("UtilizadorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UtilizadorId"));

                    b.Property<string>("Aniversario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Biografia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UtilizadorId");

                    b.ToTable("Utilizadores");
                });

            modelBuilder.Entity("AvaliacaoAnime", b =>
                {
                    b.HasOne("Utilizador", "Utilizador")
                        .WithMany("AvaliacoesAnime")
                        .HasForeignKey("UtilizadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("AvaliacaoListaUtilizador", b =>
                {
                    b.HasOne("ListaUtilizador", "ListaUtilizador")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("ListaUtilizadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Utilizador", "Utilizador")
                        .WithMany("AvaliacoesListas")
                        .HasForeignKey("UtilizadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ListaUtilizador");

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("ListaAnime", b =>
                {
                    b.HasOne("ListaUtilizador", "ListaUtilizador")
                        .WithMany("ListaAnimes")
                        .HasForeignKey("ListaUtilizadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ListaUtilizador");
                });

            modelBuilder.Entity("ListaUtilizador", b =>
                {
                    b.HasOne("Utilizador", "Utilizador")
                        .WithMany("Listas")
                        .HasForeignKey("UtilizadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("ListaUtilizador", b =>
                {
                    b.Navigation("Avaliacoes");

                    b.Navigation("ListaAnimes");
                });

            modelBuilder.Entity("Utilizador", b =>
                {
                    b.Navigation("AvaliacoesAnime");

                    b.Navigation("AvaliacoesListas");

                    b.Navigation("Listas");
                });
#pragma warning restore 612, 618
        }
    }
}
