// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

#nullable disable

namespace MyAnimeCollection.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250117180224_AddDateCreatedToAvaliationModels")]
    partial class AddDateCreatedToAvaliationModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Models.AnimeListModel", b =>
                {
                    b.Property<int>("AnimeListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnimeListId"));

                    b.Property<int>("AnimeId")
                        .HasColumnType("int");

                    b.HasKey("AnimeListId");

                    b.ToTable("AnimeLists");
                });

            modelBuilder.Entity("Models.UserAnimeAvaliationModel", b =>
                {
                    b.Property<int>("UserAnimeAvaliationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserAnimeAvaliationId"));

                    b.Property<int>("AnimeId")
                        .HasColumnType("int");

                    b.Property<float>("Avaliation")
                        .HasColumnType("real");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserAnimeAvaliationId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAnimeAvaliations");
                });

            modelBuilder.Entity("Models.UserListAvaliationModel", b =>
                {
                    b.Property<int>("UserListAvaliationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserListAvaliationId"));

                    b.Property<float>("Avaliation")
                        .HasColumnType("real");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("UserListId")
                        .HasColumnType("int");

                    b.HasKey("UserListAvaliationId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserListId");

                    b.ToTable("UserListAvaliations");
                });

            modelBuilder.Entity("Models.UserListModel", b =>
                {
                    b.Property<int>("UserListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserListId"));

                    b.Property<int>("AnimeListId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserListId");

                    b.HasIndex("AnimeListId");

                    b.HasIndex("UserId");

                    b.ToTable("UserLists");
                });

            modelBuilder.Entity("Models.UserModel", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Models.UserAnimeAvaliationModel", b =>
                {
                    b.HasOne("Models.UserModel", "User")
                        .WithMany("UserAnimeAvaliation")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Models.UserListAvaliationModel", b =>
                {
                    b.HasOne("Models.UserModel", "User")
                        .WithMany("UserListAvaliation")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Models.UserListModel", "UserList")
                        .WithMany()
                        .HasForeignKey("UserListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("UserList");
                });

            modelBuilder.Entity("Models.UserListModel", b =>
                {
                    b.HasOne("Models.AnimeListModel", "AnimeList")
                        .WithMany("UserList")
                        .HasForeignKey("AnimeListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.UserModel", "User")
                        .WithMany("UserList")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AnimeList");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Models.AnimeListModel", b =>
                {
                    b.Navigation("UserList");
                });

            modelBuilder.Entity("Models.UserModel", b =>
                {
                    b.Navigation("UserAnimeAvaliation");

                    b.Navigation("UserList");

                    b.Navigation("UserListAvaliation");
                });
#pragma warning restore 612, 618
        }
    }
}
